const INDIAN_LANGUAGES = [
  { code: "hi-IN",  label: "हिंदी",          name: "Hindi"},
  { code: "en-IN",  label: "English",         name: "English"},
  { code: "bn-IN",  label: "বাংলা",           name: "Bengali"},
  { code: "te-IN",  label: "తెలుగు",          name: "Telugu"},
  { code: "mr-IN",  label: "मराठी",           name: "Marathi"},
  { code: "ta-IN",  label: "தமிழ்",           name: "Tamil"},
  { code: "gu-IN",  label: "ગુજરાતી",         name: "Gujarati"},
  { code: "kn-IN",  label: "ಕನ್ನಡ",           name: "Kannada"},
  { code: "ml-IN",  label: "മലയാളം",          name: "Malayalam"},
  { code: "pa-IN",  label: "ਪੰਜਾਬੀ",          name: "Punjabi"},
  { code: "or-IN",  label: "ଓଡ଼ିଆ",           name: "Odia"},
  { code: "as-IN",  label: "অসমীয়া",         name: "Assamese"},
  { code: "ur-IN",  label: "اردو",            name: "Urdu"},
  { code: "mai-IN", label: "मैथिली",          name: "Maithili"},
  { code: "kok-IN", label: "कोंकणी",          name: "Konkani"},
  { code: "doi-IN", label: "डोगरी",           name: "Dogri"},
  { code: "ks-IN",  label: "کٲشُر",           name: "Kashmiri"},
  { code: "sd-IN",  label: "سنڌي",            name: "Sindhi"},
  { code: "ne-IN",  label: "नेपाली",          name: "Nepali"},
  { code: "sa-IN",  label: "संस्कृतम्",       name: "Sanskrit"},
  { code: "mni-IN", label: "ꯃꯩꯇꯩꯂꯣꯟ",        name: "Manipuri"},
  { code: "sat-IN", label: "ᱥᱟᱱᱛᱟᱲᱤ",        name: "Santali"},
  { code: "brx-IN", label: "बर'",             name: "Bodo"}
];
